name: Update README

on:
  push:
    paths:
      - 'Job_dataset.json'
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install project dependencies
        run: npm install
        
      - name: Install dependencies
        run: npm install jsonfile
        
      - name: Run UpdateReadme.js
        run: node UpdateReadme.js

      - name: Commit and push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
